regions:
  - eu-north-1
  - ap-south-1
  - eu-west-3
  - eu-west-2
  - eu-west-1
  - ap-northeast-2
  - ap-northeast-1
  - sa-east-1
  - ca-central-1
  - ap-southeast-1
  - ap-southeast-2
  - eu-central-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  - global

account-blocklist:
  - "999999999999"

resource-types:
  excludes:
    - IAMLoginProfile
    - IAMOpenIDConnectProvider
    - IAMPolicy
    - IAMRolePolicy
    - IAMRolePolicyAttachment
    - IAMVirtualMFADevice
    - SNSSubscription

accounts:
  "907317471167":
    filters:
      IAMUser:
      - "darren"
      IAMUserPolicyAttachment:
      - "darren -> AdministratorAccess"
      IAMUserAccessKey:
      - "darren -> AKIA5GQCV467SH4RLMIN"
      SNSTopic:
      - property : TopicARN
        value: "arn:aws:sns:us-east-1:907317471167:58860"
      LambdaFunction:
      - "DoiT-Management-Stack-NotificationFunction-v3nsgwwwD78y"
      CloudFormationStack:
      - property : Name
        value: "DoiT-Management-Stack"
      CloudWatchLogsLogGroup:
      - "/aws/lambda/DoiT-Management-Stack-NotificationFunction-v3nsgwwwD78y"
      - "/aws/lambda/UserManagementBackend-Dev-Stateless-APIHandler-lwK0udIDAIre"
      IAMRole:
      - "OrganizationAccountAccessRole"
      - "DoiT_Management_Role_DO-NOT-DELETE"
      - "DoiT-SupportVM839WPV"
      - "DoiT-Management-Stack-NotificationFunctionRole-1R0IFA2B8PJFQ"
      - "CloudHealth"
